[project]
name = "linear-atten-res"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cupy-cuda12x>=13.6.0",
    "numpy>=2.3.3",
    "torch>=2.8.0",
]
